
package com.innodealing.bpms.domain;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSSynServiceImplService", targetNamespace = "http://service.admin.sso.pop.czt.cn/", wsdlLocation = "http://114.215.25.76:8000/soap/syn?wsdl")
public class WSSynServiceImplService
    extends Service
{

    private final static URL WSSYNSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSYNSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WSSYNSERVICEIMPLSERVICE_QNAME = new QName("http://service.admin.sso.pop.czt.cn/", "WSSynServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://114.215.25.76:8000/soap/syn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSYNSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WSSYNSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WSSynServiceImplService() {
        super(__getWsdlLocation(), WSSYNSERVICEIMPLSERVICE_QNAME);
    }

    public WSSynServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSYNSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSSynServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WSSYNSERVICEIMPLSERVICE_QNAME);
    }

    public WSSynServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSYNSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSSynServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSynServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSSynService
     */
    @WebEndpoint(name = "WSSynServiceImplPort")
    public WSSynService getWSSynServiceImplPort() {
        return super.getPort(new QName("http://service.admin.sso.pop.czt.cn/", "WSSynServiceImplPort"), WSSynService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSynService
     */
    @WebEndpoint(name = "WSSynServiceImplPort")
    public WSSynService getWSSynServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.admin.sso.pop.czt.cn/", "WSSynServiceImplPort"), WSSynService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSYNSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WSSYNSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WSSYNSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
